//! Small helpers shared across modules.

use std::time::{SystemTime, UNIX_EPOCH};

use md5::{Digest, Md5};
use rand::Rng;
use serde_json::Value;

/// Current unix timestamp in seconds.
pub fn now_secs() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| i64::try_from(d.as_secs()).unwrap_or(i64::MAX))
        .unwrap_or_default()
}

/// Current unix timestamp in milliseconds.
pub fn now_millis() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| i64::try_from(d.as_millis()).unwrap_or(i64::MAX))
        .unwrap_or_default()
}

/// Break a unix timestamp into UTC `(year, month, day, hour, minute, second)`.
#[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
pub fn utc_datetime(ts: i64) -> (i64, u32, u32, u32, u32, u32) {
    let days = ts.div_euclid(86_400);
    let secs = ts.rem_euclid(86_400);
    // Howard Hinnant's civil_from_days.
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let month = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    let year = yoe + era * 400 + i64::from(month <= 2);
    (year, month, day, (secs / 3600) as u32, (secs % 3600 / 60) as u32, (secs % 60) as u32)
}

/// Day number (days since epoch) in China Standard Time (UTC+8).
///
/// QQ Music servers live in UTC+8; daily session rotation follows that day.
pub fn china_day(ts: i64) -> i64 {
    (ts + 8 * 3600).div_euclid(86_400)
}

/// Hex encoded MD5 of the concatenation of all parts.
pub fn calc_md5<I, T>(parts: I) -> String
where
    I: IntoIterator<Item = T>,
    T: AsRef<[u8]>,
{
    let mut hasher = Md5::new();
    for part in parts {
        hasher.update(part.as_ref());
    }
    hex::encode(hasher.finalize())
}

/// Random 32 character hex GUID (UUID4 without dashes).
pub fn get_guid() -> String {
    let mut bytes: [u8; 16] = rand::rng().random();
    bytes[6] = (bytes[6] & 0x0F) | 0x40;
    bytes[8] = (bytes[8] & 0x3F) | 0x80;
    hex::encode(bytes)
}

/// `hash33` used to compute `g_tk`.
pub fn hash33(s: &str, seed: u64) -> i64 {
    let h = s.chars().fold(seed, |h, c| (h << 5).wrapping_add(h).wrapping_add(u64::from(u32::from(c))));
    i64::try_from(h & 0x7FFF_FFFF).unwrap_or_default()
}

/// Random search id as generated by the web client.
pub fn get_search_id() -> String {
    let mut rng = rand::rng();
    let e: u128 = rng.random_range(1..=20);
    let t = e * 18_014_398_509_481_984;
    let n = u128::from(rng.random_range(0..=4_194_304_u32)) * 4_294_967_296;
    let r = u128::try_from(now_millis()).unwrap_or_default() % (24 * 60 * 60 * 1000);
    (t + n + r).to_string()
}

/// Recursively convert booleans into `0`/`1`.
pub fn bool_to_int(value: &Value) -> Value {
    match value {
        Value::Bool(b) => Value::from(u8::from(*b)),
        Value::Array(items) => Value::Array(items.iter().map(bool_to_int).collect()),
        Value::Object(map) => Value::Object(map.iter().map(|(k, v)| (k.clone(), bool_to_int(v))).collect()),
        other => other.clone(),
    }
}

/// XML escape (`&`, `<`, `>`, `"`), matching `xml.sax.saxutils.escape`.
pub fn xml_escape(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for c in input.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            other => out.push(other),
        }
    }
    out
}

/// Convert a [`serde_json::Value`] scalar to the string form used in `comm`.
pub fn value_to_comm_string(value: &Value) -> Option<String> {
    match value {
        Value::Null => None,
        Value::String(s) => Some(s.clone()),
        Value::Bool(b) => Some(if *b { "True" } else { "False" }.to_string()),
        other => Some(other.to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn md5_concatenates() {
        assert_eq!(calc_md5(["a", "bc"]), calc_md5(["abc"]));
        assert_eq!(calc_md5(["abc"]), "900150983cd24fb0d6963f7d28e17f72");
        assert_eq!(calc_md5::<[&[u8]; 0], &[u8]>([]), "d41d8cd98f00b204e9800998ecf8427e");
    }

    #[test]
    fn utc_datetime_conversion() {
        assert_eq!(utc_datetime(0), (1970, 1, 1, 0, 0, 0));
        assert_eq!(utc_datetime(951_782_400), (2000, 2, 29, 0, 0, 0));
        assert_eq!(utc_datetime(1_791_266_255), (2026, 10, 6, 5, 57, 35));
        assert_eq!(utc_datetime(-1), (1969, 12, 31, 23, 59, 59));
    }

    #[test]
    fn china_day_boundaries() {
        // 2026-10-06 15:59:59 UTC == 23:59:59 CST, next second is a new day.
        let ts = 1_791_302_399;
        assert_eq!(china_day(ts) + 1, china_day(ts + 1));
        assert_eq!(china_day(ts), china_day(ts - 3600 * 23));
    }

    #[test]
    fn guid_shape() {
        let guid = get_guid();
        assert_eq!(guid.len(), 32);
        assert!(guid.chars().all(|c| c.is_ascii_hexdigit()));
        assert_ne!(guid, get_guid());
    }

    #[test]
    fn hash33_matches_python() {
        // python: hash33("abc", 5381) / hash33("W_X_long_key_value", 5381)
        assert_eq!(hash33("", 5381), 5381);
        assert_eq!(hash33("abc", 5381), 193_485_963);
        // long strings overflow 64 bits; only the low 31 bits matter
        let long = "Q_H_L_63k3NpcLbUo5u0Dd8QW3xvjPvu3dGQ7HrXMfZ4QgK9n1mIwa3-ZnS0OgQ";
        assert_eq!(hash33(long, 5381), 637_970_813);
        assert_eq!(hash33("中文key", 5381), 1_179_827_618);
    }

    #[test]
    fn search_id_is_numeric() {
        let id = get_search_id();
        assert!(id.parse::<u128>().is_ok());
        assert!(id.len() >= 17);
    }

    #[test]
    fn bool_to_int_is_recursive() {
        let value = json!({"a": true, "b": [false, {"c": true}], "d": "true", "e": 1});
        assert_eq!(bool_to_int(&value), json!({"a": 1, "b": [0, {"c": 1}], "d": "true", "e": 1}));
    }

    #[test]
    fn escape() {
        assert_eq!(xml_escape(r#"a&b<c>"d""#), "a&amp;b&lt;c&gt;&quot;d&quot;");
        assert_eq!(xml_escape("V2408A"), "V2408A");
    }

    #[test]
    fn comm_strings() {
        assert_eq!(value_to_comm_string(&json!(1)), Some("1".into()));
        assert_eq!(value_to_comm_string(&json!("x")), Some("x".into()));
        assert_eq!(value_to_comm_string(&json!(true)), Some("True".into()));
        assert_eq!(value_to_comm_string(&Value::Null), None);
    }
}
